### ISSUE TITLE
NameError: global name 'hd' is not defined

### ISSUE THREAD

**Issue by cancan101** [ashima/pdf-table-extract#3] opened 2013-08-08 03:35 UTC
Running the following command:

```
python extracttab.py  -i ~/Downloads/HIST-PRICES.pdf -o ~/Downloads/HIST-PRICES.csv -p 1 -t table_csv
```

using the file found here: http://www.ico.org/historical/2010-19/PDF/HIST-PRICES.pdf leads to:

```
Traceback (most recent call last):
  File "extracttab.py", line 487, in <module>
    } [ args.t ](cells,args.page)
  File "extracttab.py", line 431, in o_table_csv
    ] for x in range(len(pgs))
NameError: global name 'hd' is not defined
```

**Comment by eelsirhc** [comment] 2013-08-15 19:37
There are two problems here. The first is that the csv table generator was not getting the correct variables to make the table (the missing hd, also vd and pgs), so would never work even if cells_csv and others worked (fixed in 13c58a2). The second is that the page needs to be cropped to remove spurious lines caused by the header/footer. If you update the code to the latest version, and crop the page first to isolate the table it should work.

Without cropping and running 

```
python extracttab.py -i ./HIST-PRICES.pdf -p 1 -checkcells -o bad.pnm -colmult 10.0  ; convert bad.pnm bad.png
```

![bad](https://f.cloud.github.com/assets/1069709/970969/e02792d2-05df-11e3-944d-72ebe6e5e7eb.png)

and

 cropping 1 inch from each edge

```
python extracttab.py -i ./HIST-PRICES.pdf -p 1 -checkcells -o good.pnm -colmult 10.0 -c 1:1:-1:-1 ; convert good.pnm good.png
```

![good](https://f.cloud.github.com/assets/1069709/970970/e03a3e1e-05df-11e3-8c59-733327e7a6b1.png)

Running your command with the crop added should work.

**Closed as completed** 2013-09-20 21:25 UTC
